### ISSUE TITLE
Can't navigate in mobile browser

### ISSUE THREAD

**Issue by eranchetz** [LeaVerou/inspire.js#146]
Seems like there is now way to navigate between slides on mobile devices.

**Comment by enociz** [comment]
I found this too

**Comment by LeaVerou** [comment]
There is one workaround, though it's not ideal. There is always an on-screen navigation, which becomes visible on iframe slides and the like. You can show it always on mobile. Something like:

```css
@media (/* media query to detect mobile */) {
  #onscreen-nav { display: block !important }
}
```
